version: '3.1'

services:
  backend:
    build: backend/
    container_name: backend
    restart: always
    ports:
      - 3000:3000
    networks: 
      - network 
    depends_on: [db]     
  frontend:
    build: frontend/
    container_name: frontend
    restart: always
    ports:
      - 80:80   
    networks: 
      - network          
  portainer_app:
    container_name: Portainer
    image: portainer/portainer:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports: 
      - 9000:9000
    networks: 
      - network 
    depends_on: [backend, frontend,db]       
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306 
networks:
  network:
    driver: bridge 